[package]
name = "malefic"
version = "0.0.3"
edition = "2021"
build = "build.rs"

[lib]
name = "malefic_dll"
path = "src/lib.rs"
crate-type = ["staticlib", "cdylib"]

[features]
default = ["beacon"]

bind = ["malefic-core/bind"]
beacon = []

[dependencies]
cfg-if = "1.0"
async-trait = "0.1.83"
futures = "0.3.31"
obfstr = "0.4.3"
anyhow = "1.0.81"
lazy_static = "1.4.0"

malefic-core = { path = "../malefic-core", features = [ "default" ] }
malefic-modules = { path = "../malefic-modules"}
malefic-helper = { path= "../malefic-helper", features = [ "default" ] }
malefic-proto = { path = "../malefic-proto" }

[dependencies.async-std]
version = "1.7.0"
features = ["unstable", "attributes"]

[build-dependencies]
lazy_static = "1.4.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
